import { Token } from "../../lexer";

export interface Node {
  type: NodeType;
  token?: Token;
}

export enum NodeType {
  PROGRAM,
  IMPORT_DECLARATION,
  TYPE_DEFINITION,
  FUNCTION_DEFINITION,
  MAIN_FUNCTION,
  IF_STATEMENT,
  FOR_STATEMENT,
  RETURN_STATEMENT,
  LET_STATEMENT,
  EXPRESSION_STATEMENT,
  GOM_TYPE,
  ARGUMENT_ITEM,
  FUNCTION_RETURN_TYPE,
  EXPR_BASIC,
  EXPR_BRACKETED,
  ASSIGNMENT,
  ACCESS,
  CALL,
  COMPARISON,
  SUM,
  QUOT,
  EXPO,
  TERM,
  TERMINAL,
}
